[package]
name = "arith"
version = "0.1.0"
edition = "2024"
description = "A really basic language which supports arithmetic"
[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
